# Generated by Django 3.1.4 on 2021-01-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='city',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='help',
            name='state',
        ),
    ]
